name: gopay_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  google_fonts: ^6.2.1
  dotted_line: ^3.2.3
  get: ^4.7.2
  linear_progress_bar: ^1.2.0
  flutter_inset_shadow: ^2.0.3
  mobile_scanner: ^6.0.1
  carousel_slider: ^5.0.0
  torch_light: ^1.1.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  flutter_contacts: ^1.1.9+2
  permission_handler: ^12.0.0+1
  gradient_borders: ^1.0.1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  intl: ^0.20.2
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  mockito: ^5.4.6       
  build_runner: ^2.4.15

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/
